### PR TITLE
Dependency update

### PR DESCRIPTION
**Pull request by Huulivoide**
### Update library versions
* Retrofit: Kept at 2.9.0, pending Spring Boot 3
* oauth2-oidc-sdk: 9.7 → 11.12
* wiremock
  - Version update: 2.27.2 → 3.6.0
  - Switched to standalone version, to prevent Netty version conflict with Spring updates.
* Mockito
  - Version update: 3.11.1 → 5.12.0
  - Switched to core version, as the inline-mocker has been the default mocker implementation since 5.0.0.

### Migrate to Spring Boot 3
* Spring boot updated to version 3.3.0
* OpenAPI Generator upated to version 7.6.0
  - Swicthed generator to use spring-boot as lib
  - Configured Spring Boot V3 to be in use
* Updated retrofit to version 2.11.0
* Migrated from Springfox to Springdoc v2.5.0
* Support for property 'pring.session.store-type' has been removed from Spring. So it has been replaced with a custom 'session.enabled' property. (Used to disable sesisons during test runs).
* Removed superfluous `@ExtendWith(SpringExtension::class)` annotations.
* Replaced javax imports with jakarta ones.

- - -
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36)* status: 21 of 22 files reviewed, 3 unresolved discussions (waiting on @Huulivoide)

___
*[`src/main/kotlin/fi/hsl/jore4/auth/common/DatabaseProperties.kt` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36#-O-_RC8yD-d8nnqUfZdV:-O-_T_fg5l2ylKWY8f5H:b-xkmbpw) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/34e799ad5ec9451cdadedd001f86659b72290c92/src/main/kotlin/fi/hsl/jore4/auth/common/DatabaseProperties.kt#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

IMO more idiomatic way of doing this would be:

```kotlin
require(hostname.isNotEmpty(), "...")
```
</blockquote></details>

Sorry, there is an error in the previous comment. Actually, the following would be a correct suggestion:

```kotlin
require(!hostname.isNullOrBlank(), "...")
```

...but unfortunately this correction is not so easy to read.

**Review by jarkkoka — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36)* status: 21 of 22 files reviewed, 4 unresolved discussions (waiting on @Huulivoide)

___
*[`pom.xml` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36#-O-_Viox--_8YZymBfrL:-O-_Viox--_8YZymBfrM:b8zl65m) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/34e799ad5ec9451cdadedd001f86659b72290c92/pom.xml#L21)):*
> ```XML
>         <java.version>17</java.version>
> 
>         
> ```

typo: `relased` → `released`

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36)* status: 21 of 22 files reviewed, 4 unresolved discussions (waiting on @Huulivoide)

___
*[`src/main/kotlin/fi/hsl/jore4/auth/Jore4AuthApplication.kt` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36#-O-_Raak5-DD_C8OlfFW:-O-_a4I05vd4DDDQ9X1_:bj3wnzh) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/34e799ad5ec9451cdadedd001f86659b72290c92/src/main/kotlin/fi/hsl/jore4/auth/Jore4AuthApplication.kt#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

To me this call seems to be ineffective. Even though a db property is empty or completely missing, the expected error messages (`Assert.hasText(...)` do not appear in startup at least when I tested locally.)
</blockquote></details>

I tested this again more thoroughly and it seems that when the property (eg `db.name`) is empty it works. However, if a db property is missing, these assertion messages are ineffective.

**Review by jarkkoka — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36)* status: 21 of 22 files reviewed, 4 unresolved discussions (waiting on @Huulivoide)

___
*[`src/main/kotlin/fi/hsl/jore4/auth/common/DatabaseProperties.kt` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36#-O-_RC8yD-d8nnqUfZdV:-O-_aZ0yEarHGRhM-en8:br1b42e) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/34e799ad5ec9451cdadedd001f86659b72290c92/src/main/kotlin/fi/hsl/jore4/auth/common/DatabaseProperties.kt#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Sorry, there is an error in the previous comment. Actually, the following would be a correct suggestion:

```kotlin
require(!hostname.isNullOrBlank(), "...")
```

...but unfortunately this correction is not so easy to read.
</blockquote></details>

...or even more correctly:

```kotlin
require(!name.isNullOrBlank()) { "..." }
```

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36)* status: 18 of 23 files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/auth/Jore4AuthApplication.kt` line 23 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36#-O-_Raak5-DD_C8OlfFW:-O-_eGPq1Xn2QOkAxcjC:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/34e799ad5ec9451cdadedd001f86659b72290c92/src/main/kotlin/fi/hsl/jore4/auth/Jore4AuthApplication.kt#L23)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

I tested this again more thoroughly and it seems that when the property (eg `db.name`) is empty it works. However, if a db property is missing, these assertion messages are ineffective.
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/auth/common/DatabaseProperties.kt` line 21 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36#-O-_RC8yD-d8nnqUfZdV:-O-_eHj0B4TT6NFCfN9V:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/34e799ad5ec9451cdadedd001f86659b72290c92/src/main/kotlin/fi/hsl/jore4/auth/common/DatabaseProperties.kt#L21)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

...or even more correctly:

```kotlin
require(!name.isNullOrBlank()) { "..." }
```
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 22 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/36)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Huulivoide)

**Pull request merged**
