### PR TITLE
Persistent session

### PR DESCRIPTION
**Pull request by jschummer**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)

### CODE REVIEW

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[docker/init-database.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MgoqxcGEpozjTm9j5mV:-MgoqxcGEpozjTm9j5mW:bfp8zr7) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/init-database.sh#L5)):*
> ```Shell
> 
> psql --username "$POSTGRES_USER" -v ON_ERROR_STOP=1 <<-EOF
>     CREATE DATABASE auth_session;
> ```

Let's rather name the database as `jore4` and then create a schema under with the name `auth_session` as that would be closer to reality. Also, I'd like to see how to set up spring to use a specific schema for storing a session ;)
___
*[docker/postgres.env, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-Mgosqpt1kaKxCAEKRPM:-Mgosqpt1kaKxCAEKRPN:b-18k6fl) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/postgres.env#L1)):*
> ```Shell
> POSTGRES_USER=postgres
> ```

please rather just add all these variables to the docker-compose directly. It's just complicating things if env variables are coming from multiple source
___
*[profiles/prod/config.properties, line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-Mgos4j74TonaSfe8oXn:-Mgos4j74TonaSfe8oXo:beb5arv) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/profiles/prod/config.properties#L41)):*
> ```INI
> ############################################
> spring.session.store-type=jdbc
> spring.datasource.url=
> ```

please also document these configuration parameters to the readme's "Docker reference" section as they are essential when deploying this app to Kubernetes

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[docker/init-database.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MgoqxcGEpozjTm9j5mV:-MhEH8PP79ZejuvqFAm-:b-82qc39) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/init-database.sh#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Let's rather name the database as `jore4` and then create a schema under with the name `auth_session` as that would be closer to reality. Also, I'd like to see how to set up spring to use a specific schema for storing a session ;)
</blockquote></details>

I'm not sure it'd be better to have the auth backend use the same db as e.g. hasura. After all the data is very different, and there is no connection between the spring session data and our application data. They should definitely use the same postgresql instance, but I'm really not sure about the database.

Anyway, in case we do want to use an own schema for the sessions, that should be quite easily done using the spring datasource `currentSchema` parameter, as pointed out here: https://stackoverflow.com/a/42975622
___
*[profiles/prod/config.properties, line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-Mgos4j74TonaSfe8oXn:-MhEU7SA92rOYjoLg2b1:bte478x) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/profiles/prod/config.properties#L41)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please also document these configuration parameters to the readme's "Docker reference" section as they are essential when deploying this app to Kubernetes
</blockquote></details>

Good point, added those now.
___
*[docker/postgres.env, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-Mgosqpt1kaKxCAEKRPM:-MhEOuG09g2w4Le0P6Np:b41r2aw) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/postgres.env#L1)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

please rather just add all these variables to the docker-compose directly. It's just complicating things if env variables are coming from multiple source
</blockquote></details>

Yes, you're right. I was trying to prevent duplicates (the db username and password), but then the file contained definitions which were not needed for the application. Placed the definitions straight in the docker-compose file now :+1:

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[docker/init-database.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MgoqxcGEpozjTm9j5mV:-MhHiOxd5Zxs-3PviROl:b-uz0p9k) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/init-database.sh#L5)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I'm not sure it'd be better to have the auth backend use the same db as e.g. hasura. After all the data is very different, and there is no connection between the spring session data and our application data. They should definitely use the same postgresql instance, but I'm really not sure about the database.

Anyway, in case we do want to use an own schema for the sessions, that should be quite easily done using the spring datasource `currentSchema` parameter, as pointed out here: https://stackoverflow.com/a/42975622
</blockquote></details>

Databases are expensive in Azure, let's not spin up new ones :) I think schemas should provide good enough separation of access
___
*[profiles/prod/config.properties, line 41 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-Mgos4j74TonaSfe8oXn:-MhHiuT73I1GT4FLQ4Bv:b-ucfknh) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/profiles/prod/config.properties#L41)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Good point, added those now.
</blockquote></details>

Thanks!
___
*[docker/postgres.env, line 1 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-Mgosqpt1kaKxCAEKRPM:-MhHjBr1EExviubyBTJ5:b556ppi) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/postgres.env#L1)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Yes, you're right. I was trying to prevent duplicates (the db username and password), but then the file contained definitions which were not needed for the application. Placed the definitions straight in the docker-compose file now :+1: 
</blockquote></details>

Awesome, thanks!

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @jschummer and @pallost)

___
*[docker/init-database.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MgoqxcGEpozjTm9j5mV:-MhHkVYvDyqiz-Sdgvfd:b-3xxh72) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/init-database.sh#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Databases are expensive in Azure, let's not spin up new ones :) I think schemas should provide good enough separation of access
</blockquote></details>

I didn't mean to spin up a new postgresql instance. Is there a separate fee for databases inside the postgresql instance?

If there is, then I agree that it might not be worth the additional cost.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[docker/init-database.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MgoqxcGEpozjTm9j5mV:-MhHo0kC0t1gdVU-YotC:b-z9eb54) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/init-database.sh#L5)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I didn't mean to spin up a new postgresql instance. Is there a separate fee for databases inside the postgresql instance?

If there is, then I agree that it might not be worth the additional cost.
</blockquote></details>

Ah, that's what you mean! Well, it's possible to spin up new instances within the server... I just really don't want the additional configuration and administration hassle that comes with it... is there a special reason it shouldn't follow the data strategy every other microservice is using?

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @jschummer and @pallost)

___
*[docker/init-database.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MgoqxcGEpozjTm9j5mV:-MhIvCG-0zWpFR0sQI2A:bq2bcak) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/init-database.sh#L5)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Ah, that's what you mean! Well, it's possible to spin up new instances within the server... I just really don't want the additional configuration and administration hassle that comes with it... is there a special reason it shouldn't follow the data strategy every other microservice is using?
</blockquote></details>

Mmmh, I'm not sure we're talking about the same thing, I didn't mean additional postgresql-instances, I just meant `CREATE DATABASE auth_session`.

Or do you think that would cause administration hassle?

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @jschummer and @pallost)

___
*[docker/init-database.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MgoqxcGEpozjTm9j5mV:-MhKd4LbBcklaiMwP3Is:b28j7mi) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/init-database.sh#L5)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Mmmh, I'm not sure we're talking about the same thing, I didn't mean additional postgresql-instances, I just meant `CREATE DATABASE auth_session`.

Or do you think that would cause administration hassle?
</blockquote></details>

I now changed this to use a database named `jore4` and a schema named `auth_session`.

I also noticed that the health check does not fail, if the schema is not accessible (maybe this is actually wanted), so I added another test to check that the `login` endpoint does not fail.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @jschummer)

___
*[README.md, line 101 at r3](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MhMz-Ax-WH_m6Vmwzg4:-MhMz-Ax-WH_m6Vmwzg5:bnh8d5) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/b5c30f6c464f1af62fef0e1bd7269640b3879975/README.md#L101)):*
> ```Markdown
> | api.path.prefix            | API_PATH_PREFIX            | api-path-prefix            | /api                    | Base URL of the API within the container              |
> | api.path.prefix.public     | API_PATH_PREFIX_PUBLIC     | api-path-prefix-public     | /api/auth               | Exposed base URL for API (e.g. from browser)          |
> | spring.datasource.url      | SPRING_DATASOURCE_URL      | spring-datasource-url      | jdbc:postgresql://postgres-host:5432/auth_session_db?currentSchema=auth_session_schema | Persistent session database connection URL |
> ```

you updated this too with a schema example.. thanks!
___
*[docker/init-database.sh, line 5 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MgoqxcGEpozjTm9j5mV:-MhMzPB97LhfBHkEi-fX:brujzsz) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/553223cd319bfd5a17d09f5febd0887ee8d6e24d/docker/init-database.sh#L5)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I now changed this to use a database named `jore4` and a schema named `auth_session`.

I also noticed that the health check does not fail, if the schema is not accessible (maybe this is actually wanted), so I added another test to check that the `login` endpoint does not fail.
</blockquote></details>

OK, thanks!
___
*[profiles/dev/config.properties, line 44 at r3](https://reviewable.io/reviews/hsldevcom/jore4-auth/10#-MhMzXWO-Q0xkIDzYO21:-MhMzXWO-Q0xkIDzYO22:b14w1uz) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/b5c30f6c464f1af62fef0e1bd7269640b3879975/profiles/dev/config.properties#L44)):*
> ```INI
> ############################################
> spring.session.store-type=jdbc
> spring.datasource.url=jdbc:postgresql://localhost:5432/auth
> ```

isn't this missing the schema reference? Also, the password is auth_pass and the port is 6432.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/10)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @jschummer)

**Pull request merged**
