### PR TITLE
Dockerize application

### PR DESCRIPTION
**Pull request by pallost**
Closes https://github.com/HSLdevcom/jore4/issues/380
Closes https://github.com/HSLdevcom/jore4/issues/382

---
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6)

### CODE REVIEW

**Review by jschummer — CHANGES_REQUESTED** [review]
A lot of good stuff here :-)

Some things to think about, might be that I just didn't understand how they work...

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-:-Mcid2El24jHuZwjYgnc:b-sn2bn5)* status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @pallost)

___
*[README.md, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-MciYLczDy6T29VY_rVB:-MciYLczDy6T29VY_rVC:b-vqu2np) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L18)):*
> ```
> 1
> ```
Are you sure this works? At least in IDEA it does not display as '2', apparently the above code snippet (and / or new line) breaks the automatic numbering.
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-MciaFkR-Bx1xH5-M98j:-MciaFkR-Bx1xH5-M98k:biuyau3) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L32)):*
> ```
> auth
> ```
"auth backend"? (actually in two places on that line)
___
*[README.md, line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-MciaTxNAymI7z7LKoUn:-MciaTxNAymI7z7LKoUo:bfxhins) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L33)):*
> ```
> Runs frontend and auth through nginx proxy that maps UI to localhost:3301/ and auth to localhost:3301/api/auth
> Frontend directly accessible through localhost:3302 and Auth backend through localhost:3200
> ```
Not much of a show stopper, but wouldn't mind some more articles in there ;-) ("Runs _the_ frontend" etc)
___
*[README.md, line 82 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mciculf3tWMCCI8q5q5:-Mciculf3tWMCCI8q5q6:bg5gfjw) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L82)):*
> ```
> sprint
> ```
"spring"
___
*[.github/workflows/docker-build.yml, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-McicQpj8W4NNtvzN0x6:-McicQpj8W4NNtvzN0x7:b-2mjxqc) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/docker-build.yml#L32)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>       - name: Set environment variables
>         run: |
>           # Docker Hub uses lowercase so use a bashism to convert.
>           echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
>           # Docker tags can use only some special characters.
>           echo "COMMIT_ID=$(echo "${BRANCH_NAME}" | tr -C '0-9a-zA-Z._' '-')-${GITHUB_SHA}" >> $GITHUB_ENV
> ```
</details>

I suppose this will work similarly for other repos in the future?

Is there any (good) way of sharing these actions or some logic of them between repos?
___
*[.github/workflows/test-docker-compose.yml, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mci_APj5An_SpJSfvmg:-Mci_APj5An_SpJSfvmh:b-3hxlj7) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L18)):*
> ```
>  docker-compose up -d
> ```
I otherwise like the idea of testing that the dockerized version starts up and does something.

But here we also start the proxy and UI, is that necessary or a good idea? Would it be better to use `docker run`?
___
*[.github/workflows/test-docker-compose.yml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mci_Yqs3S5-iJRuRrOv:-Mci_Yqs3S5-iJRuRrOw:bxiz7us) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L20)):*
> ```
> Verify that UI is up and running
> ```
See above, do we want to test that here?
___
*[.github/workflows/test-docker-compose.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mcic-AOE5GhFW2aTqT0:-Mcic-AP0VTcvYKhd5Il:b-h0ja0i) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L23)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>           for i in {1..20}; do
>             curl --fail http://localhost:3301 --output /dev/null --silent && break
>             sleep 5
>             echo $i
>           done
> ```
</details>

Does this really fail (through return code I assume) if no connection can be established?

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6)* status: 0 of 12 files reviewed, 8 unresolved discussions (waiting on @jschummer)

___
*[README.md, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-MciYLczDy6T29VY_rVB:-McsM_d7Dg2ZHpOXYygX:b-livlzs) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L18)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> 1
> ```
Are you sure this works? At least in IDEA it does not display as '2', apparently the above code snippet (and / or new line) breaks the automatic numbering.
</blockquote></details>

it should, at least I've been using this extensively also in other markdown files :) For me, also IDEA renders it as '2'
___
*[README.md, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-MciaFkR-Bx1xH5-M98j:-McsHKbE8aXHMsdlCshJ:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L32)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> auth
> ```
"auth backend"? (actually in two places on that line)
</blockquote></details>

Done.
___
*[README.md, line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-MciaTxNAymI7z7LKoUn:-McsHbA77AbfKqLaoYSl:b-oh8yss) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L33)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> Runs frontend and auth through nginx proxy that maps UI to localhost:3301/ and auth to localhost:3301/api/auth
> Frontend directly accessible through localhost:3302 and Auth backend through localhost:3200
> ```
Not much of a show stopper, but wouldn't mind some more articles in there ;-) ("Runs _the_ frontend" etc)
</blockquote></details>

okay, this is getting into nitpicking, I won't fix :P
___
*[README.md, line 82 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mciculf3tWMCCI8q5q5:-McsHxS2BpUzb0ZEiemA:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L82)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> sprint
> ```
"spring"
</blockquote></details>

Done.
___
*[.github/workflows/docker-build.yml, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-McicQpj8W4NNtvzN0x6:-McsHzT17qjutx3_ctJf:b-qlur6j) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/docker-build.yml#L32)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>       - name: Set environment variables
>         run: |
>           # Docker Hub uses lowercase so use a bashism to convert.
>           echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
>           # Docker tags can use only some special characters.
>           echo "COMMIT_ID=$(echo "${BRANCH_NAME}" | tr -C '0-9a-zA-Z._' '-')-${GITHUB_SHA}" >> $GITHUB_ENV
> ```
I suppose this will work similarly for other repos in the future?

Is there any (good) way of sharing these actions or some logic of them between repos?
</blockquote></details>

could extract this as a github action to e.g. jore4-tools repository. I created a ticket about this as it does not really belong to the scope of this pull request: https://github.com/HSLdevcom/jore4/issues/402
___
*[.github/workflows/test-docker-compose.yml, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mci_APj5An_SpJSfvmg:-McsIko21wgAV9OGtaUm:b9yv67y) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L18)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>  docker-compose up -d
> ```
I otherwise like the idea of testing that the dockerized version starts up and does something.

But here we also start the proxy and UI, is that necessary or a good idea? Would it be better to use `docker run`?
</blockquote></details>

As auth backend is not really a standalone microservice but heavily depends on the context (UI, Ingress, etc), it's better to test it in context. With docker-compose we can test that:
- the service can be built and run in docker
- the service can be parameterized with environment variables and OIDC initialization works
- the service can be proxied through an ingress with the help of API_PATH_PREFIX parameters and mapped to proper url paths

this might be somewhat possible to test with docker run too, but that does not show that this microservice also works in a context
___
*[.github/workflows/test-docker-compose.yml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mci_Yqs3S5-iJRuRrOv:-McsKgdN9csITTKlz4yD:bmsw4ux) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L20)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
> Verify that UI is up and running
> ```
See above, do we want to test that here?
</blockquote></details>

I answered in the previous comment
___
*[.github/workflows/test-docker-compose.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mcic-AOE5GhFW2aTqT0:-McsLzuz-2eUtHotp5x_:b-bzo52l) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L23)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

> ```
>           for i in {1..20}; do
>             curl --fail http://localhost:3301 --output /dev/null --silent && break
>             sleep 5
>             echo $i
>           done
> ```
Does this really fail (through return code I assume) if no connection can be established?
</blockquote></details>

yepp, curl --fail only succeeds if the url does exist and the response code is 2xx or 3xx

**Review by jschummer — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @pallost)

___
*[README.md, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-MciYLczDy6T29VY_rVB:-McwWqys1ZsvfR8fLeNi:b-byl8mi) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

it should, at least I've been using this extensively also in other markdown files :) For me, also IDEA renders it as '2'
</blockquote></details>

Mmh, ok. Apparently there was one newline too many (because I wanted to have separate paragraphs), which broke the automatic numbering. :+1: 
___
*[README.md, line 33 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-MciaTxNAymI7z7LKoUn:-McwXjjL3MKarFUerHBR:b1d8edv) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/README.md#L33)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

okay, this is getting into nitpicking, I won't fix :P
</blockquote></details>

I won't insist. :-) But in general, I think documentation should use correct grammar, just so it's easy to read.
___
*[.github/workflows/docker-build.yml, line 32 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-McicQpj8W4NNtvzN0x6:-Mcw_NVPDrqt0Hgog6Dv:b932u7s) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/docker-build.yml#L32)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

could extract this as a github action to e.g. jore4-tools repository. I created a ticket about this as it does not really belong to the scope of this pull request: https://github.com/HSLdevcom/jore4/issues/402
</blockquote></details>

Ok, nice :+1: 
___
*[.github/workflows/test-docker-compose.yml, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mci_APj5An_SpJSfvmg:-Mcw_Y2Z9T4LEvwLdEqs:b-2eaubj) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L18)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

As auth backend is not really a standalone microservice but heavily depends on the context (UI, Ingress, etc), it's better to test it in context. With docker-compose we can test that:
- the service can be built and run in docker
- the service can be parameterized with environment variables and OIDC initialization works
- the service can be proxied through an ingress with the help of API_PATH_PREFIX parameters and mapped to proper url paths

this might be somewhat possible to test with docker run too, but that does not show that this microservice also works in a context
</blockquote></details>

I don't see how the UI is used in any of the 3 examples you gave.

Also, I think the "whole package" should (and will, I think) be tested in e2e tests.

The only reason I can see for the tests, which involve the UI, to fail, is that the UI is broken. Is there something I don't get here?
___
*[.github/workflows/test-docker-compose.yml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mci_Yqs3S5-iJRuRrOv:-McwZpb52ky817tqJOXq:b-omf9ik) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L20)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

I answered in the previous comment
</blockquote></details>

In my opinion, this was not answered. How does verifying that the UI is up test something related to the auth backend?
___
*[.github/workflows/test-docker-compose.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mcic-AOE5GhFW2aTqT0:-McwZAx24k1hXID-q7UK:b-g7k307) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

yepp, curl --fail only succeeds if the url does exist and the response code is 2xx or 3xx
</blockquote></details>

Yes, but if I get this correct, the return code of the loop will be 0 in any case. I some cases it'll just exit sooner than in others.

So I don't understand how the workflow knows if this step succeeded...

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[.github/workflows/test-docker-compose.yml, line 18 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mci_APj5An_SpJSfvmg:-McxV92cBaSpTyADrhLA:b-jzxdus) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L18)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I don't see how the UI is used in any of the 3 examples you gave.

Also, I think the "whole package" should (and will, I think) be tested in e2e tests.

The only reason I can see for the tests, which involve the UI, to fail, is that the UI is broken. Is there something I don't get here?
</blockquote></details>

alright, I'll only start up the auth service from the docker-compose then...
___
*[.github/workflows/test-docker-compose.yml, line 20 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mci_Yqs3S5-iJRuRrOv:-McxVGCl4zUdG2TUg2qB:b441eke) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L20)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

In my opinion, this was not answered. How does verifying that the UI is up test something related to the auth backend?
</blockquote></details>

only starting up the auth backend from now on
___
*[.github/workflows/test-docker-compose.yml, line 23 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mcic-AOE5GhFW2aTqT0:-McxVJQ76pFCu11ZY29Y:b-k64p8s) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/548e023a384f0482c71455a060ed1ea208d79b6d/.github/workflows/test-docker-compose.yml#L23)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Yes, but if I get this correct, the return code of the loop will be 0 in any case. I some cases it'll just exit sooner than in others.

So I don't understand how the workflow knows if this step succeeded...
</blockquote></details>

Good catch! I haven't noticed this before and have already been using this code widely in many github workflows... I have actually exported this code section to its own github action: https://github.com/HSLdevcom/jore4-tools/pull/2

**Review by lassemaatta — COMMENTED** [review]
> Reviewed 7 of 12 files at r1, 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6)* status: 11 of 12 files reviewed, 5 unresolved discussions (waiting on @jschummer and @pallost)

___
*[Dockerfile, line 9 at r10](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-McxhtwH-IJf3YoqdipV:-McxhtwH-IJf3YoqdipW:byzx257) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/ec61d52aebc0e25ec08b93337e0d2db0d2c46bb1/Dockerfile#L9)):*
> ```
> go-offline
> ```

This works ok'ish most of the time, but I believe [this](https://github.com/qaware/go-offline-maven-plugin) is better. E.g. something like

```dockerfile
RUN mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
```
___
*[pom.xml, line 26 at r10](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mcxj1PC4vqGqiI_q25n:-Mcxj1PC4vqGqiI_q25o:b-6plo67) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/ec61d52aebc0e25ec08b93337e0d2db0d2c46bb1/pom.xml#L26)):*
> ```
> <management.endpoints.web.exposure.include>health</management.endpoints.web.exposure.include>
> ```

Are you sure this line actually does anything? For this to work, I think you need to refer to this in some `application.properties` file or something like that so that Maven takes this property and rewrites the `.properties` files before injecting them into the `.jar`.

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @lassemaatta and @pallost)

___
*[pom.xml, line 26 at r10](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mcxj1PC4vqGqiI_q25n:-McyGJ0pCm_IkRtdv7oR:b-iv9pcw) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/ec61d52aebc0e25ec08b93337e0d2db0d2c46bb1/pom.xml#L26)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> <management.endpoints.web.exposure.include>health</management.endpoints.web.exposure.include>
> ```

Are you sure this line actually does anything? For this to work, I think you need to refer to this in some `application.properties` file or something like that so that Maven takes this property and rewrites the `.properties` files before injecting them into the `.jar`.
</blockquote></details>

I think he has a point. Maybe this should just be define din the application.properties file, might be the simplest solution. (I don't think we need to make this dependant on the build profile.)

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @lassemaatta)

___
*[Dockerfile, line 9 at r10](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-McxhtwH-IJf3YoqdipV:-MgdlnTKANE0-LGb0R92:b-896fix) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/ec61d52aebc0e25ec08b93337e0d2db0d2c46bb1/Dockerfile#L9)):*
<details><summary><i>Previously, lassemaatta (Lasse Määttä) wrote…</i></summary><blockquote>

> ```
> go-offline
> ```

This works ok'ish most of the time, but I believe [this](https://github.com/qaware/go-offline-maven-plugin) is better. E.g. something like

```dockerfile
RUN mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies
```
</blockquote></details>

Done.
___
*[pom.xml, line 26 at r10](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-Mcxj1PC4vqGqiI_q25n:-Mgdm7Ck3P2L-lC0cTbh:b23el86) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/ec61d52aebc0e25ec08b93337e0d2db0d2c46bb1/pom.xml#L26)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

I think he has a point. Maybe this should just be define din the application.properties file, might be the simplest solution. (I don't think we need to make this dependant on the build profile.)
</blockquote></details>

OK, I just learned about application.properties :) I'll move it there

**Review by jschummer — APPROVED** [review]
Very nice, please integrate! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/6#-:-MgfGDT73WxmLMMuTFcy:b-skpscc)* status: 9 of 13 files reviewed, 2 unresolved discussions (waiting on @lassemaatta)

**Pull request merged**
