### PR TITLE
Define user info fields

### PR DESCRIPTION
**Pull request by jschummer**
This change is [Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/7)

### CODE REVIEW

**Review by pallost — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/7)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @jschummer)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-MgiasxD4juPvHmwJsTR:-MgiasxE90c4bClyWwvf:bopn272) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/0dddc31f8100a74d3dd041e79e1e25ad6b19d1b4/-- commits#L2)):*
Is this a file or what...?

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/7)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @jschummer)

___
*[src/main/kotlin/fi/hsl/jore4/auth/userInfo/SafeUserInfoApiDTO.kt, line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-Mgo9TkZE_K74YQ7q4kr:-Mgo9TkZE_K74YQ7q4ks:b-pucnhi) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/kotlin/fi/hsl/jore4/auth/userInfo/SafeUserInfoApiDTO.kt#L23)):*
> ```Kotlin
>                 it.familyName = "XXX"
>                 it.fullName = "XXX"
>                 it.permissions = this.permissions
> ```

As other values might leak into this as well as the OIDC service changes (e.g. phone number, email address), would be safer to include values (like id, permissions, jwt fields) instead of excluding
___
*[src/main/openapi/api.yaml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-MgoFdYD238j7eJ-HJVM:-MgoFdYD238j7eJ-HJVN:bmikrh) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/openapi/api.yaml#L8)):*
> ```YAML
>     name: EUPL 1.2
> servers:
>   - url: https://jore.hsl.fi/api/auth/public/v1
> ```

This is not going to work in DEV or TEST stages. Is it possible to set this value dynamically? Or is it possible to just set a relative url, e.g. `/api/auth/public/v1`?

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/7)* status: 0 of 11 files reviewed, 3 unresolved discussions (waiting on @pallost)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-MgiasxD4juPvHmwJsTR:-Mgp2b0g6z8whzJXoYDV:bmelyu9) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/0dddc31f8100a74d3dd041e79e1e25ad6b19d1b4/-- commits#L2)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

Is this a file or what...?
</blockquote></details>

Good question :-D It's at least no file created by me.

I think this is a new feature of reviewable, but looks a bit strange, you're right...
___
*[src/main/kotlin/fi/hsl/jore4/auth/userInfo/SafeUserInfoApiDTO.kt, line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-Mgo9TkZE_K74YQ7q4kr:-Mgp2wMM4dvt3EVAJRf5:bpbwcdh) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/kotlin/fi/hsl/jore4/auth/userInfo/SafeUserInfoApiDTO.kt#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

As other values might leak into this as well as the OIDC service changes (e.g. phone number, email address), would be safer to include values (like id, permissions, jwt fields) instead of excluding
</blockquote></details>

Well, this is kind of explicit including. If a new property is added to the DTO without any addition here, it'll be output as being unassigned.

So when a new property is added, we'll need to add here either `it.newProp = this.newProp` or `it.newProp = "xxx"`. Not optimal, but at least it's not leaked by accident.
___
*[src/main/openapi/api.yaml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-MgoFdYD238j7eJ-HJVM:-Mgp3RG5BhUSsHCQi5KY:bxtpi11) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/openapi/api.yaml#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

This is not going to work in DEV or TEST stages. Is it possible to set this value dynamically? Or is it possible to just set a relative url, e.g. `/api/auth/public/v1`?
</blockquote></details>

If I understood it right, this is not really possible.

It is possible to parametrize this property, but then you'd have to specify the parameter always when the API definitions (or docs!) are created. And since we want to use the same docker images for all environments, this makes as little sense as specifying some environment's URL here...

But this is not used during code generation, this is really more for informative purposes.

**Review by pallost — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/7)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @jschummer)

___
*[src/main/kotlin/fi/hsl/jore4/auth/userInfo/SafeUserInfoApiDTO.kt, line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-Mgo9TkZE_K74YQ7q4kr:-MhHh3tnBqHJoAjhNxQp:b2u06jz) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/kotlin/fi/hsl/jore4/auth/userInfo/SafeUserInfoApiDTO.kt#L23)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Well, this is kind of explicit including. If a new property is added to the DTO without any addition here, it'll be output as being unassigned.

So when a new property is added, we'll need to add here either `it.newProp = this.newProp` or `it.newProp = "xxx"`. Not optimal, but at least it's not leaked by accident.
</blockquote></details>

how does DTO work in java? If the /userinfo response body contains a new attribute and is read to this "limited" DTO, every unmapped, unknown attributes will be thrown away? In that case this solution is fine :+1: 
___
*[src/main/openapi/api.yaml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-MgoFdYD238j7eJ-HJVM:-MhHhphn9hPjbWuZXsYi:b-20jbz8) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/openapi/api.yaml#L8)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

If I understood it right, this is not really possible.

It is possible to parametrize this property, but then you'd have to specify the parameter always when the API definitions (or docs!) are created. And since we want to use the same docker images for all environments, this makes as little sense as specifying some environment's URL here...

But this is not used during code generation, this is really more for informative purposes.
</blockquote></details>

So when using the swagger UI in the browser to call the endpoints, this url won't be used? I understand that parametrizing this field is not possible, at least not practical.

**Review by jschummer — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/7)* status: 0 of 11 files reviewed, 2 unresolved discussions (waiting on @pallost)

___
*[src/main/kotlin/fi/hsl/jore4/auth/userInfo/SafeUserInfoApiDTO.kt, line 23 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-Mgo9TkZE_K74YQ7q4kr:-MhHlBRv5FlYh8r96wEG:b-jjl8dw) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/kotlin/fi/hsl/jore4/auth/userInfo/SafeUserInfoApiDTO.kt#L23)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

how does DTO work in java? If the /userinfo response body contains a new attribute and is read to this "limited" DTO, every unmapped, unknown attributes will be thrown away? In that case this solution is fine :+1: 
</blockquote></details>

Basically yes, every attribute not listed here will not be output at all, so there shouldn't be any leak.
___
*[src/main/openapi/api.yaml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-MgoFdYD238j7eJ-HJVM:-MhHlKCq8QdRl_GW8DN3:br2u4yu) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/openapi/api.yaml#L8)):*
<details><summary><i>Previously, pallost (Tamas Pallos) wrote…</i></summary><blockquote>

So when using the swagger UI in the browser to call the endpoints, this url won't be used? I understand that parametrizing this field is not possible, at least not practical. 
</blockquote></details>

Well, until now we don't have swagger UI in use, so maybe we don't need to worry about that? Not sure how it would work though, maybe it could be configured to use the base path of the server it's running on.

**Review by pallost — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/hsldevcom/jore4-auth/7)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @jschummer)

___
*[src/main/openapi/api.yaml, line 8 at r2](https://reviewable.io/reviews/hsldevcom/jore4-auth/7#-MgoFdYD238j7eJ-HJVM:-MhHm5zW54FERS7lMTAS:b-39m9x6) ([raw file](https://github.com/hsldevcom/jore4-auth/blob/627fba3a715791bd0842cfce96795b83727bced6/src/main/openapi/api.yaml#L8)):*
<details><summary><i>Previously, jschummer wrote…</i></summary><blockquote>

Well, until now we don't have swagger UI in use, so maybe we don't need to worry about that? Not sure how it would work though, maybe it could be configured to use the base path of the server it's running on.
</blockquote></details>

alright, let's worry about this later then...

**Pull request merged**
