### PR TITLE
Enable ktlint & replace some deprecated API calls

### PR DESCRIPTION
**Pull request by Huulivoide**
This change is [Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37)

### CODE REVIEW

**Review by jarkkoka — CHANGES_REQUESTED** [review]
Looks good! Two comments left. One is about the comma style, which we've wanted to avoid in other Java/Kotlin repositories.

> Reviewed 26 of 27 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37#-:-O-jImBcCDy51VFGyF6Q:bg5qjxf)* status: 26 of 27 files reviewed, 2 unresolved discussions (waiting on @Huulivoide)

___
*[`src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCAuthInterceptor.kt` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37#-O-jH5cSEk92-LGeOxLT:-O-jH5cSEk92-LGeOxLU:b-lwwei0) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/8364eb9ded8b8f88e9cd59e0dd70d21cd9612b11/src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCAuthInterceptor.kt#L34)):*
> ```Kotlin
>     private fun proceedWithAccessToken(
>         chain: Interceptor.Chain,
>         accessToken: AccessToken,
> ```

In <jore4-hastus> repository, we have set these properties in `.editorconfig` to get rid of trailing commas.

```
[*.{kt,kts}]
ij_kotlin_allow_trailing_comma_on_call_site=false
ij_kotlin_allow_trailing_comma=false
```
___
*[`src/main/kotlin/fi/hsl/jore4/auth/oidc/PublicKeyLocator.kt` line 81 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37#-O-jHb1J8CJruswrQFZ7:-O-jHb1J8CJruswrQFZ8:b-9ossbm) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/8364eb9ded8b8f88e9cd59e0dd70d21cd9612b11/src/main/kotlin/fi/hsl/jore4/auth/oidc/PublicKeyLocator.kt#L81)):*
> ```Kotlin
>     }
> 
>     private fun resolveHeaderType(header: Header?): String {
> ```

You can move this stateless method to a companion object. The body and also be much more condensed (Kotlin-ish), like:

```kotlin
 private fun resolveHeaderType(header: Header?): String = header?.javaClass?.canonicalName ?: "null"
```

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37)* status: 9 of 28 files reviewed, 2 unresolved discussions (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCAuthInterceptor.kt` line 34 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37#-O-jH5cSEk92-LGeOxLT:-O-j_Bzy9-Chuft0_AZ0:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/8364eb9ded8b8f88e9cd59e0dd70d21cd9612b11/src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCAuthInterceptor.kt#L34)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

In <jore4-hastus> repository, we have set these properties in `.editorconfig` to get rid of trailing commas.

```
[*.{kt,kts}]
ij_kotlin_allow_trailing_comma_on_call_site=false
ij_kotlin_allow_trailing_comma=false
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/fi/hsl/jore4/auth/oidc/PublicKeyLocator.kt` line 81 at r1](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37#-O-jHb1J8CJruswrQFZ7:-O-j_DFd280YY0CLjAPJ:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/8364eb9ded8b8f88e9cd59e0dd70d21cd9612b11/src/main/kotlin/fi/hsl/jore4/auth/oidc/PublicKeyLocator.kt#L81)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

You can move this stateless method to a companion object. The body and also be much more condensed (Kotlin-ish), like:

```kotlin
 private fun resolveHeaderType(header: Header?): String = header?.javaClass?.canonicalName ?: "null"
```
</blockquote></details>

Done.

**Review by jarkkoka — APPROVED** [review]
> Reviewed 1 of 27 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37)* status: all files reviewed, 1 unresolved discussion (waiting on @Huulivoide)

___
*[`src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCAuthInterceptor.kt` line 118 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37#-O-jok4B1tS_bPRaAPU8:-O-jok4C2tI4wWvr5hTp:bvjxwe8) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/c1d66f7a1c9f760d19df9112331de6e4eceb8d14/src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCAuthInterceptor.kt#L118)):*
> ```Kotlin
>                 userTokenSet,
>                 storeUserTokenSet = {
>                         newTokenSet ->
> ```

Looks a bit odd. IMO this would look better in this form:

```kotlin
                storeUserTokenSet = { newTokenSet ->
```

**Review by Huulivoide — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37)* status: 27 of 28 files reviewed, 1 unresolved discussion (waiting on @jarkkoka)

___
*[`src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCAuthInterceptor.kt` line 118 at r2](https://reviewable.io/reviews/HSLdevcom/jore4-auth/37#-O-jok4B1tS_bPRaAPU8:-O-jwyGV6Y_dP8Ak4w5s:b-896fix) ([raw file](https://github.com/HSLdevcom/jore4-auth/blob/c1d66f7a1c9f760d19df9112331de6e4eceb8d14/src/main/kotlin/fi/hsl/jore4/auth/oidc/OIDCAuthInterceptor.kt#L118)):*
<details><summary><i>Previously, jarkkoka (Jarkko Kaura) wrote…</i></summary><blockquote>

Looks a bit odd. IMO this would look better in this form:

```kotlin
                storeUserTokenSet = { newTokenSet ->
```
</blockquote></details>

Done.

**Pull request merged**
